/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akiin
 */
public class functionsPage extends javax.swing.JFrame {

       /**
     * Creates new form productPage
     */
    public functionsPage() {
        initComponents();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPasswordField1 = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        topMenuPanel = new javax.swing.JPanel();
        stocksSectionButton = new javax.swing.JButton();
        salesSectionButton = new javax.swing.JButton();
        transactionsSectionbutton = new javax.swing.JButton();
        productsSectionButton = new javax.swing.JButton();
        accountsSectionButton = new javax.swing.JButton();
        returnHomeButton = new javax.swing.JButton();
        lowerMainPanel = new javax.swing.JPanel();
        stocksSection = new javax.swing.JPanel();
        stocksSectionLabel = new javax.swing.JLabel();
        salesSection = new javax.swing.JPanel();
        salesLabel = new javax.swing.JLabel();
        transactionsSection = new javax.swing.JPanel();
        transactionsLabel = new javax.swing.JLabel();
        productsSection = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel productManagementTitleLabel = new javax.swing.JLabel();
        javax.swing.JLabel itemCodeLabel = new javax.swing.JLabel();
        itemCodeTextField = new javax.swing.JTextField();
        itemNameTextField = new javax.swing.JTextField();
        javax.swing.JLabel itemNameLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        javax.swing.JLabel descriptionLabel = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        javax.swing.JLabel categoryLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        javax.swing.JLabel priceLabel = new javax.swing.JLabel();
        stocksTextField = new javax.swing.JTextField();
        javax.swing.JLabel stocksLabel = new javax.swing.JLabel();
        javax.swing.JPanel multiChoicePanel = new javax.swing.JPanel();
        javax.swing.JButton confirmProductButton = new javax.swing.JButton();
        javax.swing.JButton clearProductButton = new javax.swing.JButton();
        javax.swing.JButton deleteProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productListTable = new javax.swing.JTable();
        accountsSection = new javax.swing.JPanel();
        accountsLabel = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topMenuPanel.setBackground(new java.awt.Color(204, 255, 204));

        stocksSectionButton.setBackground(new java.awt.Color(204, 255, 255));
        stocksSectionButton.setText("Stocks");
        stocksSectionButton.setBorder(null);
        stocksSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocksSectionButtonActionPerformed(evt);
            }
        });

        salesSectionButton.setBackground(new java.awt.Color(204, 255, 255));
        salesSectionButton.setText("Sales");
        salesSectionButton.setBorder(null);
        salesSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesSectionButtonActionPerformed(evt);
            }
        });

        transactionsSectionbutton.setBackground(new java.awt.Color(204, 255, 255));
        transactionsSectionbutton.setText("Transactions");
        transactionsSectionbutton.setBorder(null);
        transactionsSectionbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsSectionbuttonActionPerformed(evt);
            }
        });

        productsSectionButton.setBackground(new java.awt.Color(204, 255, 255));
        productsSectionButton.setText("Products");
        productsSectionButton.setBorder(null);
        productsSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsSectionButtonActionPerformed(evt);
            }
        });

        accountsSectionButton.setBackground(new java.awt.Color(204, 255, 255));
        accountsSectionButton.setText("Accounts");
        accountsSectionButton.setBorder(null);
        accountsSectionButton.setMaximumSize(new java.awt.Dimension(47, 16));
        accountsSectionButton.setMinimumSize(new java.awt.Dimension(47, 16));
        accountsSectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsSectionButtonActionPerformed(evt);
            }
        });

        returnHomeButton.setBackground(new java.awt.Color(204, 255, 255));
        returnHomeButton.setText("Return");
        returnHomeButton.setBorder(null);
        returnHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topMenuPanelLayout = new javax.swing.GroupLayout(topMenuPanel);
        topMenuPanel.setLayout(topMenuPanelLayout);
        topMenuPanelLayout.setHorizontalGroup(
            topMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMenuPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(stocksSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salesSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transactionsSectionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productsSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountsSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addComponent(returnHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        topMenuPanelLayout.setVerticalGroup(
            topMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(topMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stocksSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionsSectionbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productsSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountsSectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(topMenuPanel, java.awt.BorderLayout.PAGE_START);

        lowerMainPanel.setBackground(new java.awt.Color(97, 214, 150));
        lowerMainPanel.setLayout(new java.awt.CardLayout());

        stocksSection.setBackground(new java.awt.Color(153, 255, 153));

        stocksSectionLabel.setBackground(new java.awt.Color(153, 255, 153));
        stocksSectionLabel.setText("STOCKS");

        javax.swing.GroupLayout stocksSectionLayout = new javax.swing.GroupLayout(stocksSection);
        stocksSection.setLayout(stocksSectionLayout);
        stocksSectionLayout.setHorizontalGroup(
            stocksSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stocksSectionLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(stocksSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        stocksSectionLayout.setVerticalGroup(
            stocksSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stocksSectionLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(stocksSectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        lowerMainPanel.add(stocksSection, "card5");

        salesSection.setBackground(new java.awt.Color(153, 255, 153));

        salesLabel.setBackground(new java.awt.Color(153, 255, 153));
        salesLabel.setText("SALES");

        javax.swing.GroupLayout salesSectionLayout = new javax.swing.GroupLayout(salesSection);
        salesSection.setLayout(salesSectionLayout);
        salesSectionLayout.setHorizontalGroup(
            salesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesSectionLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        salesSectionLayout.setVerticalGroup(
            salesSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesSectionLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        lowerMainPanel.add(salesSection, "card4");

        transactionsSection.setBackground(new java.awt.Color(153, 255, 153));

        transactionsLabel.setBackground(new java.awt.Color(153, 255, 153));
        transactionsLabel.setText("TRANSACTIONS");

        javax.swing.GroupLayout transactionsSectionLayout = new javax.swing.GroupLayout(transactionsSection);
        transactionsSection.setLayout(transactionsSectionLayout);
        transactionsSectionLayout.setHorizontalGroup(
            transactionsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transactionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(837, Short.MAX_VALUE))
        );
        transactionsSectionLayout.setVerticalGroup(
            transactionsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsSectionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(transactionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        lowerMainPanel.add(transactionsSection, "card3");

        productsSection.setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        productManagementTitleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        productManagementTitleLabel.setText("PRODUCT MANAGEMENT:");

        itemCodeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        itemCodeLabel.setText("Item Code");

        itemCodeTextField.setText("jTextField1");
        itemCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTextFieldActionPerformed(evt);
            }
        });

        itemNameTextField.setText("jTextField1");

        itemNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        itemNameLabel.setText("Item Name");

        descriptionTextField.setText("jTextField1");

        descriptionLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        descriptionLabel.setText("Description");

        categoryTextField.setText("jTextField1");

        categoryLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        categoryLabel.setText("Category");

        priceTextField.setText("jTextField1");

        priceLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        priceLabel.setText("Price");

        stocksTextField.setText("jTextField1");

        stocksLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        stocksLabel.setText("Stocks");

        multiChoicePanel.setBackground(new java.awt.Color(153, 255, 153));

        confirmProductButton.setBackground(new java.awt.Color(204, 255, 255));
        confirmProductButton.setText("Confirm");
        confirmProductButton.setBorder(null);
        confirmProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmProductButtonActionPerformed(evt);
            }
        });

        clearProductButton.setBackground(new java.awt.Color(204, 255, 255));
        clearProductButton.setText("Clear");
        clearProductButton.setBorder(null);
        clearProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearProductButtonActionPerformed(evt);
            }
        });

        deleteProductButton.setBackground(new java.awt.Color(204, 255, 255));
        deleteProductButton.setText("DELETE");
        deleteProductButton.setBorder(null);
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout multiChoicePanelLayout = new javax.swing.GroupLayout(multiChoicePanel);
        multiChoicePanel.setLayout(multiChoicePanelLayout);
        multiChoicePanelLayout.setHorizontalGroup(
            multiChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiChoicePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        multiChoicePanelLayout.setVerticalGroup(
            multiChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiChoicePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(multiChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productManagementTitleLabel)
                    .addComponent(itemCodeLabel)
                    .addComponent(itemCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameLabel)
                    .addComponent(descriptionLabel)
                    .addComponent(priceLabel)
                    .addComponent(stocksLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel)
                    .addComponent(stocksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(productManagementTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemNameLabel)
                .addGap(12, 12, 12)
                .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(categoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(priceLabel)
                .addGap(12, 12, 12)
                .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stocksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stocksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(multiChoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        productListTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        productListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Description", "Category", "Price", "Stocks"
            }
        ));
        jScrollPane1.setViewportView(productListTable);

        javax.swing.GroupLayout productsSectionLayout = new javax.swing.GroupLayout(productsSection);
        productsSection.setLayout(productsSectionLayout);
        productsSectionLayout.setHorizontalGroup(
            productsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsSectionLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        productsSectionLayout.setVerticalGroup(
            productsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lowerMainPanel.add(productsSection, "card2");

        accountsSection.setBackground(new java.awt.Color(153, 255, 153));

        accountsLabel.setText("ACCOUNTS");

        javax.swing.GroupLayout accountsSectionLayout = new javax.swing.GroupLayout(accountsSection);
        accountsSection.setLayout(accountsSectionLayout);
        accountsSectionLayout.setHorizontalGroup(
            accountsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsSectionLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(accountsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        accountsSectionLayout.setVerticalGroup(
            accountsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsSectionLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(accountsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        lowerMainPanel.add(accountsSection, "card6");

        getContentPane().add(lowerMainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void stocksSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocksSectionButtonActionPerformed
       changeSections(stocksSection); //calls method to change to stocks section
    }//GEN-LAST:event_stocksSectionButtonActionPerformed

    private void salesSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesSectionButtonActionPerformed
       changeSections(salesSection); //calls method to change to sales section
    }//GEN-LAST:event_salesSectionButtonActionPerformed

    private void transactionsSectionbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsSectionbuttonActionPerformed
       changeSections(transactionsSection); //calls method to change to trans section
    }//GEN-LAST:event_transactionsSectionbuttonActionPerformed

    private void productsSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsSectionButtonActionPerformed
       changeSections(productsSection); //calls method to change to prod section
    }//GEN-LAST:event_productsSectionButtonActionPerformed

    private void accountsSectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsSectionButtonActionPerformed
       changeSections(accountsSection); //calls method to change to acc section
    }//GEN-LAST:event_accountsSectionButtonActionPerformed
    
        // these methods allow program to navigate to sections from the home page. since the Jframe classes are private
            
            public JPanel stocksSectionsCall(){
                changeSections(stocksSection);
                return null;
            }
    
            public JPanel salesSectionsCall(){
                changeSections(salesSection);
                return null;
            }
            public JPanel transactionsSectionsCall(){
                changeSections(transactionsSection);
                return null;
            }
            
            public JPanel productsSectionsCall(){
                changeSections(productsSection);
                return null;
            }
            
            public JPanel accountsSectionsCall(){
                changeSections(accountsSection);
                return null;
            }
        
    
    public void changeSections(JPanel section) { //this method allows the program to change pages when called. used for buttons.
        lowerMainPanel.removeAll();
        lowerMainPanel.add(section);
        lowerMainPanel.repaint();
        lowerMainPanel.revalidate();
    }
    
    private void itemCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTextFieldActionPerformed

    
    
    
    
    
    //products Section functions. A
   
    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        
        int row = productListTable.getSelectedRow();
        
        
        if(row < 0){
            JOptionPane.showMessageDialog(this, "You did not select a product. Please select desired product to delete.",    
                                                             "No row chosen", JOptionPane.ERROR_MESSAGE);
        }
        else {
            
        int confirmInput = JOptionPane.showConfirmDialog(this, "are you sure you want to delete product?",    
                                                 "Confirm Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            //PLEASE DECLARE CONFIRMINPUT AT START OF PROGRAM BEFORE PUTTING THIS HERE IM JUST LAZY LOL
            if (confirmInput == JOptionPane.YES_OPTION ){
            DefaultTableModel model =(DefaultTableModel) productListTable.getModel();
            model.removeRow(row);
            JOptionPane.showMessageDialog(this, "Sucessful product deletion.",    
                                                             "Product Deletion Successful.", JOptionPane.INFORMATION_MESSAGE);
            }
            else if (confirmInput == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "Deletion Cancelled.",    
                                                             "Product Deletion Cancelled.", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void confirmProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmProductButtonActionPerformed
       
        // all this takes all values inputted from text fields to be added to table.
        String itemCode = "000001"; // make this code enumerate up for every product added
        String itemName = itemNameTextField.getText();
        String description = descriptionTextField.getText();
        String category = categoryTextField.getText();
        String price = priceTextField.getText();
        String stocks = stocksTextField.getText();
        
        //below adds the product details to table
        
        if (itemName.isEmpty() || description.isEmpty() || category.isEmpty() || price.isEmpty() || stocks.isEmpty() ){ //checks for incomplete product listing
            JOptionPane.showMessageDialog(this, "Lacking product details! Please fill out all product details.",    
                                                             "Incomplete Details", JOptionPane.ERROR_MESSAGE);
        } 
        else { //the actual code adding the products to the table
            DefaultTableModel model = (DefaultTableModel) productListTable.getModel();
            model.addRow (new Object[]{itemCode, itemName, description, category, price, stocks});
        }
        
        
    }//GEN-LAST:event_confirmProductButtonActionPerformed

    private void clearProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearProductButtonActionPerformed
        itemCodeTextField.setText("");
        itemNameTextField.setText("");
        descriptionTextField.setText("");
        categoryTextField.setText("");
        priceTextField.setText("");
        stocksTextField.setText("");
    }//GEN-LAST:event_clearProductButtonActionPerformed

    private void returnHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeButtonActionPerformed
        this.dispose();
       
        homeFrame homePage = new homeFrame(); //allows program to use homepag
        homePage.setVisible(true);
        homePage.setLocationRelativeTo(null);
    }//GEN-LAST:event_returnHomeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(functionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(functionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(functionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(functionsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new functionsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountsLabel;
    private javax.swing.JPanel accountsSection;
    private javax.swing.JButton accountsSectionButton;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField itemCodeTextField;
    private javax.swing.JTextField itemNameTextField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lowerMainPanel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTable productListTable;
    private javax.swing.JPanel productsSection;
    private javax.swing.JButton productsSectionButton;
    private javax.swing.JButton returnHomeButton;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JPanel salesSection;
    private javax.swing.JButton salesSectionButton;
    private javax.swing.JPanel stocksSection;
    private javax.swing.JButton stocksSectionButton;
    private javax.swing.JLabel stocksSectionLabel;
    private javax.swing.JTextField stocksTextField;
    private javax.swing.JPanel topMenuPanel;
    private javax.swing.JLabel transactionsLabel;
    private javax.swing.JPanel transactionsSection;
    private javax.swing.JButton transactionsSectionbutton;
    // End of variables declaration//GEN-END:variables

    void productsSectionButtonActionPerformed() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void changeSection(JPanel productsSection) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
